apiVersion: v1
kind: Pod
metadata:
  name: phaedra2-gateway
  labels:
    ci: phaedra2-gateway-build
spec:
  containers:
   - name: builder
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/phaedra2-build-container:latest
     securityContext:
        privileged: true
     resources:
        requests:
            memory: "1Gi"
        limits:
            memory: "2Gi"

