keycloak-base-url: http://keycloak:8080
keycloak-logout-url: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/logout
redirect-uri: http://localhost:8080/phaedra/ui/

gateway:
  user-lookup:
    client-reg-id: keycloakClientCred
    endpoint: ${keycloak-base-url}/auth/admin/realms/phaedra2/users

server:
  servlet:
    context-path: /phaedra

spring:
  webflux:
    base-path: /phaedra
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
      - RewritePath=/phaedra/*v.+/(?<service>.*service)/(?<segment>.*), /phaedra/$\{service}/$\{segment}
      - TokenRelay=
      routes:
      - id: plate-service
        uri: http://phaedra-plate-service:8080
        predicates:
        - Path=/phaedra/**/plate-service/**
      - id: platedefinition-service
        uri: http://phaedra-platedefinition-service:8080
        predicates:
        - Path=/phaedra/**/platedefinition-service/**
      - id: metadata-service
        uri: http://phaedra-metadata-service:8080
        predicates:
        - Path=/phaedra/**/metadata-service/**
      - id: protocol-service
        uri: http://phaedra-protocol-service:8080
        predicates:
        - Path=/phaedra/**/protocol-service/**
      - id: calculation-service
        uri: http://phaedra-calculation-service:8080
        predicates:
        - Path=/phaedra/**/calculation-service/**
      - id: resultdata-service
        uri: http://phaedra-resultdata-service:8080
        predicates:
        - Path=/phaedra/**/resultdata-service/**
      - id: measurement-service
        uri: http://phaedra-measurement-service:8080
        predicates:
        - Path=/phaedra/**/measurement-service/**
      - id: pipeline-service
        uri: http://phaedra-pipeline-service:8080
        predicates:
        - Path=/phaedra/**/pipeline-service/**
      - id: datacapture-service
        uri: http://phaedra-datacapture-service:8080
        predicates:
        - Path=/phaedra/**/datacapture-service/**
      - id: scriptengine-r-worker
        uri: http://phaedra-scriptengine-r-worker:8080
        predicates:
        - Path=/phaedra/**/scriptengine-r-worker/**
      - id: charting-service
        uri: http://phaedra-charting-service:8080
        predicates:
        - Path=/phaedra/**/charting-service/**
      - id: query-service
        uri: http://phaedra-query-service:8080
        predicates:
        - Path=/phaedra/**/query-service/**
      - id: ui
        uri: http://phaedra-ui:8080
        predicates:
        - Path=/phaedra/ui/**
        filters:
        - RewritePath=/phaedra/ui/(?<segment>.*), /phaedra/ui/$\{segment}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
          keycloakClientCred:
            provider: keycloak
            client-id: ${spring.security.oauth2.client.registration.keycloak.client-id}
            client-secret: ${spring.security.oauth2.client.registration.keycloak.client-secret}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            authorization-uri: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/auth
            token-uri: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/token
            user-info-uri: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: ${keycloak-base-url}/auth/realms/phaedra2/protocol/openid-connect/certs


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
