server:
  port: 3131

spring:
  application:
    name: PHAEDRA-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PHAEDRA-PROTOCOL-SERVICE
          uri: lb://PHAEDRA-PROTOCOL-SERVICE
          predicates:
            - Path=/phaedra/protocol-service/**
        - id: PHAEDRA-METADATA-SERVICE
          uri: lb://PHAEDRA-METADATA-SERVICE
          predicates:
            - Path=/phaedra/metadata-service/**
        - id: PHAEDRA-PLATE-SERVICE
          uri: lb://PHAEDRA-PLATE-SERVICE
          predicates:
            - Path=/phaedra/plate-service/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${SERVICE_REGISTRY}
